### ISSUE TITLE
The Xcode project does not load.

### ISSUE THREAD

**Issue by evermeer** [ishkawa/DataSourceKit#11]
When opening the Xcode project (Xcode 10) Then It's empty. (no files or anything else)

**Comment by ishkawa** [comment]
I guess your Xcode focuses on Report Navigator like below.
<img width="493" alt="2018-09-20 22 58 38" src="https://user-images.githubusercontent.com/966856/45823683-2c56e080-bd29-11e8-8726-d7d881ccdd02.png">

My Xcode was the same for some reasons. Command + 1 to focus on Project Navigator fixed this issue for my case.

**Comment by evermeer** [comment]
Ha! I did not noticed that. Thanks
