### ISSUE TITLE
Question: custom cell actions.

### ISSUE THREAD

**Issue by SlavinskiySergey** [ishkawa/DataSourceKit#6]
What is the preferred way to provide actions on cell?
I mean something like in https://github.com/maxsokolov/TableKit#row-actions>.
Thanks in advance.

**Comment by ishkawa** [comment]
Yes, @dehlen's explanation is exactly the same as my opinion.

**Comment by SlavinskiySergey** [comment]
@dehlen , @ishkawa .
For ex., I have two buttons on my custom cell. How to differentiate taps on each of them?
